
namespace Cinema.Movie.Movie {
    export interface HistoryRow {
        HistoryId?: number;
        UserName?: string;
        Message?: string;
        Status?: boolean;
        CastId?: number;
        CountryId?: number;
        GenreId?: number;
        ServiceId?: number;
        MovieId?: number;
        PersonId?: number;
        ImageId?: number;
        MovieCountryId?: number;
        ServicePathId?: number;
        ServiceRatingId?: number;
        MovieTagId?: number;
        TagId?: number;
        VideoId?: number;
        MovieGenreId?: number;
        CastCharacter?: string;
        CastMovieId?: number;
        CastPersonId?: number;
        CountryName?: string;
        GenreName?: string;
        GenreIcon?: string;
        ServiceName?: string;
        ServiceApi?: string;
        ServiceActive?: boolean;
        ServiceIntervalRequest?: number;
        ServiceLastEvent?: string;
        ServiceLastEventPublishDateTime?: string;
        ServiceMaxRating?: number;
        MovieTitleOriginal?: string;
        MovieTitleTranslation?: string;
        MovieUrl?: string;
        MovieDescription?: string;
        MovieYearStart?: number;
        MovieYearEnd?: number;
        MovieReleaseWorldDate?: string;
        MovieReleaseOtherDate?: string;
        MovieReleaseDvd?: string;
        MovieRuntime?: string;
        MovieCreateDateTime?: string;
        MovieUpdateDateTime?: string;
        MoviePublishDateTime?: string;
        MovieKind?: number;
        MovieRating?: number;
        MovieMpaa?: string;
        MoviePathImage?: string;
        MovieNice?: boolean;
        MovieContSeason?: number;
        MovieLastEvent?: string;
        MovieLastEventPublishDateTime?: string;
        MovieTagline?: string;
        MovieBudget?: number;
        PersonNameEn?: string;
        PersonFullNameEn?: string;
        PersonNameOther?: string;
        PersonFullNameOther?: string;
        PersonBirthDate?: string;
        PersonDeathDate?: string;
        PersonGender?: number;
        PersonAbout?: string;
        PersonPathImage?: string;
        ImagePath?: string;
        ImageMovieId?: number;
        ImagePersonId?: number;
        MovieCountryMovieId?: number;
        MovieCountryCountryId?: number;
        ServicePathPath?: string;
        ServicePathServiceId?: number;
        ServiceRatingRating?: number;
        ServiceRatingId?: number;
        ServiceRatingMovieId?: number;
        ServiceRatingServiceId?: number;
        MovieTagTagId?: number;
        MovieTagMovieId?: number;
        TagName?: string;
        VideoPath?: string;
        VideoPlayer?: number;
        VideoPathTorrent?: string;
        VideoName?: string;
        VideoTranslation?: number;
        VideoSeason?: number;
        VideoSerie?: number;
        VideoStoryline?: string;
        VideoPlannePublishDate?: string;
        VideoActualPublishDateTime?: string;
        VideoMovieId?: number;
        VideoServiceId?: number;
        MovieGenreMovieId?: number;
        MovieGenreGenreId?: number;
    }

    export namespace HistoryRow {
        export const idProperty = 'HistoryId';
        export const nameProperty = 'UserName';
        export const localTextPrefix = 'Movie.History';

        export namespace Fields {
            export declare const HistoryId;
            export declare const UserName;
            export declare const Message;
            export declare const Status;
            export declare const CastId;
            export declare const CountryId;
            export declare const GenreId;
            export declare const ServiceId;
            export declare const MovieId;
            export declare const PersonId;
            export declare const ImageId;
            export declare const MovieCountryId;
            export declare const ServicePathId;
            export declare const ServiceRatingId;
            export declare const MovieTagId;
            export declare const TagId;
            export declare const VideoId;
            export declare const MovieGenreId;
            export declare const CastCharacter: string;
            export declare const CastMovieId: string;
            export declare const CastPersonId: string;
            export declare const CountryName: string;
            export declare const GenreName: string;
            export declare const GenreIcon: string;
            export declare const ServiceName: string;
            export declare const ServiceApi: string;
            export declare const ServiceActive: string;
            export declare const ServiceIntervalRequest: string;
            export declare const ServiceLastEvent: string;
            export declare const ServiceLastEventPublishDateTime: string;
            export declare const ServiceMaxRating: string;
            export declare const MovieTitleOriginal: string;
            export declare const MovieTitleTranslation: string;
            export declare const MovieUrl: string;
            export declare const MovieDescription: string;
            export declare const MovieYearStart: string;
            export declare const MovieYearEnd: string;
            export declare const MovieReleaseWorldDate: string;
            export declare const MovieReleaseOtherDate: string;
            export declare const MovieReleaseDvd: string;
            export declare const MovieRuntime: string;
            export declare const MovieCreateDateTime: string;
            export declare const MovieUpdateDateTime: string;
            export declare const MoviePublishDateTime: string;
            export declare const MovieKind: string;
            export declare const MovieRating: string;
            export declare const MovieMpaa: string;
            export declare const MoviePathImage: string;
            export declare const MovieNice: string;
            export declare const MovieContSeason: string;
            export declare const MovieLastEvent: string;
            export declare const MovieLastEventPublishDateTime: string;
            export declare const MovieTagline: string;
            export declare const MovieBudget: string;
            export declare const PersonNameEn: string;
            export declare const PersonFullNameEn: string;
            export declare const PersonNameOther: string;
            export declare const PersonFullNameOther: string;
            export declare const PersonBirthDate: string;
            export declare const PersonDeathDate: string;
            export declare const PersonGender: string;
            export declare const PersonAbout: string;
            export declare const PersonPathImage: string;
            export declare const ImagePath: string;
            export declare const ImageMovieId: string;
            export declare const ImagePersonId: string;
            export declare const MovieCountryMovieId: string;
            export declare const MovieCountryCountryId: string;
            export declare const ServicePathPath: string;
            export declare const ServicePathServiceId: string;
            export declare const ServiceRatingRating: string;
            export declare const ServiceRatingId: string;
            export declare const ServiceRatingMovieId: string;
            export declare const ServiceRatingServiceId: string;
            export declare const MovieTagTagId: string;
            export declare const MovieTagMovieId: string;
            export declare const TagName: string;
            export declare const VideoPath: string;
            export declare const VideoPlayer: string;
            export declare const VideoPathTorrent: string;
            export declare const VideoName: string;
            export declare const VideoTranslation: string;
            export declare const VideoSeason: string;
            export declare const VideoSerie: string;
            export declare const VideoStoryline: string;
            export declare const VideoPlannePublishDate: string;
            export declare const VideoActualPublishDateTime: string;
            export declare const VideoMovieId: string;
            export declare const VideoServiceId: string;
            export declare const MovieGenreMovieId: string;
            export declare const MovieGenreGenreId: string;
        }

        ['HistoryId', 'UserName', 'Message', 'Status', 'CastId', 'CountryId', 'GenreId', 'ServiceId', 'MovieId', 'PersonId', 'ImageId', 'MovieCountryId', 'ServicePathId', 'ServiceRatingId', 'MovieTagId', 'TagId', 'VideoId', 'MovieGenreId', 'CastCharacter', 'CastMovieId', 'CastPersonId', 'CountryName', 'GenreName', 'GenreIcon', 'ServiceName', 'ServiceApi', 'ServiceActive', 'ServiceIntervalRequest', 'ServiceLastEvent', 'ServiceLastEventPublishDateTime', 'ServiceMaxRating', 'MovieTitleOriginal', 'MovieTitleTranslation', 'MovieUrl', 'MovieDescription', 'MovieYearStart', 'MovieYearEnd', 'MovieReleaseWorldDate', 'MovieReleaseOtherDate', 'MovieReleaseDvd', 'MovieRuntime', 'MovieCreateDateTime', 'MovieUpdateDateTime', 'MoviePublishDateTime', 'MovieKind', 'MovieRating', 'MovieMpaa', 'MoviePathImage', 'MovieNice', 'MovieContSeason', 'MovieLastEvent', 'MovieLastEventPublishDateTime', 'MovieTagline', 'MovieBudget', 'PersonNameEn', 'PersonFullNameEn', 'PersonNameOther', 'PersonFullNameOther', 'PersonBirthDate', 'PersonDeathDate', 'PersonGender', 'PersonAbout', 'PersonPathImage', 'ImagePath', 'ImageMovieId', 'ImagePersonId', 'MovieCountryMovieId', 'MovieCountryCountryId', 'ServicePathPath', 'ServicePathServiceId', 'ServiceRatingRating', 'ServiceRatingId', 'ServiceRatingMovieId', 'ServiceRatingServiceId', 'MovieTagTagId', 'MovieTagMovieId', 'TagName', 'VideoPath', 'VideoPlayer', 'VideoPathTorrent', 'VideoName', 'VideoTranslation', 'VideoSeason', 'VideoSerie', 'VideoStoryline', 'VideoPlannePublishDate', 'VideoActualPublishDateTime', 'VideoMovieId', 'VideoServiceId', 'MovieGenreMovieId', 'MovieGenreGenreId'].forEach(x => (<any>Fields)[x] = x);
    }
}

